### ISSUE TITLE
PrefixService Null Error

### ISSUE THREAD

**Issue by TylerFlar** [PassiveModding/Passive-BOT#12]
Hi again. I'm having a problem with your Discord.Addons.PrefixService 

> Unhandled Exception: System.NullReferenceException: The PrefixService update action was unable to find a valid PrefixDictionary document
>    at Discord.Addons.PrefixService.PrefixService.Initialize()
>    at Bot.Program.<StartAsync>d__5.MoveNext() in C:\Users\***\source\repos\Bot\Bot\Program.cs:line 93
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Foxley.Program.Main(String[] args) in C:\Users\****\source\repos\Bot\Bot\Program.cs:line 41

I've downloaded the C# file from your repos of Discord.Addons.PrefixService to step through and find the error. It shows that my service is null in Initialize()?

P.S wasn't sure which repos to post the error on but I use some code from this bot to reference PrefixService.

**Comment by PassiveModding** [comment]
Should be fixed by updating prefixservice from 1.0.3 to 1.0.4

**Comment by TylerFlar** [comment]
Did the trick. Thank you!
